name: Rust

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GLib dependencies
      run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev
      
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose
      
    - name: Check
      run: cargo check
